# Common Properties
	# The Minecraft version in the development environment
	minecraft_version=26.1
	# The minimum minecraft version (inclusive) to run this Mod
	minecraft_version_min=26.1
	# The maximum minecraft version (exclusive) to run this Mod
	minecraft_version_max=26.2
	# These Minecraft versions will be declared as supported in the publications (Optional)
	minecraft_versions_declared=26.1, 26.1.1, 26.1.2

# Mod Properties
	mod_version = 4.10.0
	dev_group = net.mobz
	archives_base_name = mobz

# Common dependencies
	cloth_config_version=26.1.154
	cloth_config_version_min=26.1.154
